CREATE TABLE IF NOT EXISTS prices (
  itemid VARCHAR(191) PRIMARY KEY,
  price DECIMAL(12, 2) NOT NULL,
  denomination VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
